package com.radouaneoubakhane.serviceinscription.util;

import com.radouaneoubakhane.serviceinscription.model.Inscription;
import com.radouaneoubakhane.serviceinscription.model.enums.*;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;

public class InscriptionDataGenerator {
    public static List<Inscription> generateInscription() {
        return List.of(
                Inscription.builder()
                .nom("Radouane")
                .prenom("Radouane")
                .genre(Gender.MALE)
                .dateNaissance(Date.from(LocalDate.of(1995, 8, 10).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                .lieuNaissance("Casablanca")
                .adresse("Casablanca")
                .telephone("0600000000")
                .cin("EE000000")
                .cne("G000000")
                .email("radouane@gmai.com")
                .filiereBac(Bac.SCIENCES_MATHS)
                .moyenneBac(15.5)
                .moyenneDiplome(16.5)
                .moyenneLicence(17.5)
                .mentionBac(Mention.BIEN)
                .anneeBac("2013")
                .etablissementBac("Lycée")
                .villeBac("Casablanca")
                .paysBac("Maroc")
                .diplomeDeust(DiplomeDEUST.MIP)
                .mentionDiplome(Mention.BIEN)
                .anneeDiplome("2015")
                .etablissementDiplome("Faculté")
                .villeDiplome("Casablanca")
                .paysDiplome("Maroc")
                .licence(Licence.INFO)
                .mentionLicence(Mention.BIEN)
                .anneeLicence("2018")
                .etablissementLicence("Faculté")
                .villeLicence("Casablanca")
                .paysLicence("Maroc")
                .isAccepted(false)
                .isRefused(false)
                .isCanceled(false)
                .diplomat(Diplomat.MST)
                .filiereId(1L)
                .build(),
                Inscription.builder()
                        .nom("Sarah")
                        .prenom("Johnson")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1998, 3, 15).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("London")
                        .adresse("123 Main Street")
                        .telephone("0700000000")
                        .cin("AB123456")
                        .cne("H123456")
                        .email("sarah.johnson@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(14.2)
                        .moyenneDiplome(15.8)
                        .moyenneLicence(16.4)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2016")
                        .etablissementBac("City High School")
                        .villeBac("London")
                        .paysBac("United Kingdom")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2018")
                        .etablissementDiplome("University College London")
                        .villeDiplome("London")
                        .paysDiplome("United Kingdom")
                        .licence(Licence.GAT)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2021")
                        .etablissementLicence("University of Oxford")
                        .villeLicence("Oxford")
                        .paysLicence("United Kingdom")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(2L)
                        .build(),
                Inscription.builder()
                        .nom("Mohammed")
                        .prenom("Ali")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1990, 11, 5).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Cairo")
                        .adresse("456 Elm Street")
                        .telephone("0100000000")
                        .cin("CD789012")
                        .cne("I789012")
                        .email("mohammed.ali@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(16.8)
                        .moyenneDiplome(17.2)
                        .moyenneLicence(18.6)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2008")
                        .etablissementBac("Nasr City School")
                        .villeBac("Cairo")
                        .paysBac("Egypt")
                        .diplomeDeust(DiplomeDEUST.GE)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2010")
                        .etablissementDiplome("Cairo University")
                        .villeDiplome("Cairo")
                        .paysDiplome("Egypt")
                        .licence(Licence.IET)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2013")
                        .etablissementLicence("American University in Cairo")
                        .villeLicence("Cairo")
                        .paysLicence("Egypt")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(3L)
                        .build(),
                Inscription.builder()
                        .nom("Sophie")
                        .prenom("Garcia")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1993, 7, 20).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Paris")
                        .adresse("789 Oak Avenue")
                        .telephone("0600000000")
                        .cin("EF345678")
                        .cne("J345678")
                        .email("sophie.garcia@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(15.6)
                        .moyenneDiplome(16.9)
                        .moyenneLicence(17.8)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2011")
                        .etablissementBac("Lycée Louis-le-Grand")
                        .villeBac("Paris")
                        .paysBac("France")
                        .diplomeDeust(DiplomeDEUST.GM)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2013")
                        .etablissementDiplome("Université Paris 1 Panthéon-Sorbonne")
                        .villeDiplome("Paris")
                        .paysDiplome("France")
                        .licence(Licence.PE)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2016")
                        .etablissementLicence("HEC Paris")
                        .villeLicence("Jouy-en-Josas")
                        .paysLicence("France")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(4L)
                        .build(),
                Inscription.builder()
                        .nom("Liam")
                        .prenom("Wilson")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1997, 12, 28).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("New York")
                        .adresse("987 Pine Street")
                        .telephone("0900000000")
                        .cin("GH901234")
                        .cne("K901234")
                        .email("liam.wilson@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(17.9)
                        .moyenneDiplome(18.3)
                        .moyenneLicence(19.1)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2015")
                        .etablissementBac("Stuyvesant High School")
                        .villeBac("New York")
                        .paysBac("United States")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2017")
                        .etablissementDiplome("Columbia University")
                        .villeDiplome("New York")
                        .paysDiplome("United States")
                        .licence(Licence.INFO)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2020")
                        .etablissementLicence("Massachusetts Institute of Technology")
                        .villeLicence("Cambridge")
                        .paysLicence("United States")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(1L)
                        .build(),
                Inscription.builder()
                        .nom("Mia")
                        .prenom("Thompson")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1992, 5, 8).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Sydney")
                        .adresse("321 Maple Road")
                        .telephone("0400000000")
                        .cin("IJ567890")
                        .cne("L567890")
                        .email("mia.thompson@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(14.7)
                        .moyenneDiplome(16.1)
                        .moyenneLicence(17.2)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2010")
                        .etablissementBac("Sydney Girls High School")
                        .villeBac("Sydney")
                        .paysBac("Australia")
                        .diplomeDeust(DiplomeDEUST.GE)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2012")
                        .etablissementDiplome("University of Sydney")
                        .villeDiplome("Sydney")
                        .paysDiplome("Australia")
                        .licence(Licence.GAT)
                        .mentionLicence(Mention.BIEN)
                        .anneeLicence("2015")
                        .etablissementLicence("University of Melbourne")
                        .villeLicence("Melbourne")
                        .paysLicence("Australia")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(2L)
                        .build(),
                Inscription.builder()
                        .nom("Noah")
                        .prenom("Harris")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1994, 9, 17).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Toronto")
                        .adresse("543 Cedar Lane")
                        .telephone("0700000000")
                        .cin("KL789012")
                        .cne("M789012")
                        .email("noah.harris@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(16.4)
                        .moyenneDiplome(17.7)
                        .moyenneLicence(18.9)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2012")
                        .etablissementBac("Marc Garneau Collegiate Institute")
                        .villeBac("Toronto")
                        .paysBac("Canada")
                        .diplomeDeust(DiplomeDEUST.GM)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2014")
                        .etablissementDiplome("University of Toronto")
                        .villeDiplome("Toronto")
                        .paysDiplome("Canada")
                        .licence(Licence.GAT)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2017")
                        .etablissementLicence("McGill University")
                        .villeLicence("Montreal")
                        .paysLicence("Canada")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(3L)
                        .build(),
                Inscription.builder()
                        .nom("Ava")
                        .prenom("Clark")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1996, 6, 12).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Melbourne")
                        .adresse("876 Birch Avenue")
                        .telephone("0900000000")
                        .cin("MN901234")
                        .cne("P901234")
                        .email("ava.clark@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(15.8)
                        .moyenneDiplome(17.3)
                        .moyenneLicence(18.2)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2014")
                        .etablissementBac("Melbourne High School")
                        .villeBac("Melbourne")
                        .paysBac("Australia")
                        .diplomeDeust(DiplomeDEUST.BCG)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2016")
                        .etablissementDiplome("Monash University")
                        .villeDiplome("Melbourne")
                        .paysDiplome("Australia")
                        .licence(Licence.GM)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2019")
                        .etablissementLicence("University of New South Wales")
                        .villeLicence("Sydney")
                        .paysLicence("Australia")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(4L)
                        .build(),
                Inscription.builder()
                        .nom("Oliver")
                        .prenom("Walker")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1991, 2, 3).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Auckland")
                        .adresse("234 Walnut Street")
                        .telephone("0400000000")
                        .cin("OP567890")
                        .cne("Q567890")
                        .email("oliver.walker@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(18.2)
                        .moyenneDiplome(18.7)
                        .moyenneLicence(19.5)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2009")
                        .etablissementBac("Auckland Grammar School")
                        .villeBac("Auckland")
                        .paysBac("New Zealand")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2011")
                        .etablissementDiplome("University of Auckland")
                        .villeDiplome("Auckland")
                        .paysDiplome("New Zealand")
                        .licence(Licence.INFO)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2014")
                        .etablissementLicence("Victoria University of Wellington")
                        .villeLicence("Wellington")
                        .paysLicence("New Zealand")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(1L)
                        .build(),
                Inscription.builder()
                        .nom("Emma")
                        .prenom("Hall")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1993, 11, 6).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("London")
                        .adresse("765 Elm Street")
                        .telephone("0700000000")
                        .cin("RS789012")
                        .cne("T789012")
                        .email("emma.hall@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(14.9)
                        .moyenneDiplome(16.3)
                        .moyenneLicence(17.4)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2011")
                        .etablissementBac("City of London School")
                        .villeBac("London")
                        .paysBac("United Kingdom")
                        .diplomeDeust(DiplomeDEUST.GM)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2013")
                        .etablissementDiplome("King's College London")
                        .villeDiplome("London")
                        .paysDiplome("United Kingdom")
                        .licence(Licence.IET)
                        .mentionLicence(Mention.BIEN)
                        .anneeLicence("2016")
                        .etablissementLicence("University of Cambridge")
                        .villeLicence("Cambridge")
                        .paysLicence("United Kingdom")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(2L)
                        .build(),
                Inscription.builder()
                        .nom("William")
                        .prenom("Baker")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1997, 4, 15).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Toronto")
                        .adresse("432 Oak Street")
                        .telephone("0800000000")
                        .cin("UV901234")
                        .cne("W901234")
                        .email("william.baker@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(16.7)
                        .moyenneDiplome(18.0)
                        .moyenneLicence(19.2)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2015")
                        .etablissementBac("Marc Garneau Collegiate Institute")
                        .villeBac("Toronto")
                        .paysBac("Canada")
                        .diplomeDeust(DiplomeDEUST.GE)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2017")
                        .etablissementDiplome("University of Toronto")
                        .villeDiplome("Toronto")
                        .paysDiplome("Canada")
                        .licence(Licence.IET)
                        .mentionLicence(Mention.TRES_BIEN)
                        .anneeLicence("2020")
                        .etablissementLicence("McGill University")
                        .villeLicence("Montreal")
                        .paysLicence("Canada")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(3L)
                        .build()
        );
    }

    public static List<Inscription> generateInscriptionDeus() {

        return List.of(
                Inscription.builder()
                .nom("Radouane")
                .prenom("Radouane")
                .genre(Gender.MALE)
                .dateNaissance(Date.from(LocalDate.of(1995, 8, 10).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                .lieuNaissance("Casablanca")
                .adresse("Casablanca")
                .telephone("0600000000")
                .cin("EE000000")
                .cne("G000000")
                .email("radouane@gmai.com")
                .filiereBac(Bac.SCIENCES_MATHS)
                .moyenneBac(15.5)
                .mentionBac(Mention.BIEN)
                .anneeBac("2013")
                .etablissementBac("Lycée")
                .villeBac("Casablanca")
                .paysBac("Maroc")
                .isAccepted(false)
                .isRefused(false)
                .isCanceled(false)
                .diplomat(Diplomat.DEUST)
                .filiereId(1L)
                .build(),
                Inscription.builder()
                        .nom("Emma")
                        .prenom("Johnson")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1998, 5, 20).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("New York")
                        .adresse("123 Main Street")
                        .telephone("555-1234")
                        .cin("AB123456")
                        .cne("G654321")
                        .email("emma.johnson@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(14.2)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2016")
                        .etablissementBac("High School")
                        .villeBac("New York")
                        .paysBac("USA")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(2L)
                        .build(),
                Inscription.builder()
                        .nom("Alexander")
                        .prenom("Smith")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1993, 10, 5).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("London")
                        .adresse("456 Park Avenue")
                        .telephone("555-5678")
                        .cin("CD987654")
                        .cne("F321654")
                        .email("alexander.smith@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(17.8)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2011")
                        .etablissementBac("Secondary School")
                        .villeBac("London")
                        .paysBac("UK")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(3L)
                        .build(),
                Inscription.builder()
                        .nom("Sophia")
                        .prenom("Brown")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1996, 3, 15).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Los Angeles")
                        .adresse("789 Elm Street")
                        .telephone("555-9012")
                        .cin("EF246810")
                        .cne("H135790")
                        .email("sophia.brown@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(16.5)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2014")
                        .etablissementBac("High School")
                        .villeBac("Los Angeles")
                        .paysBac("USA")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(4L)
                        .build(),
                Inscription.builder()
                        .nom("Noah")
                        .prenom("Miller")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1994, 7, 8).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Sydney")
                        .adresse("321 Oak Street")
                        .telephone("555-3456")
                        .cin("GH135792")
                        .cne("K246813")
                        .email("noah.miller@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(15.1)
                        .mentionBac(Mention.PASSABLE)
                        .anneeBac("2012")
                        .etablissementBac("High School")
                        .villeBac("Sydney")
                        .paysBac("Australia")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(5L)
                        .build(),
                Inscription.builder()
                        .nom("Ava")
                        .prenom("Davis")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1997, 12, 3).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Paris")
                        .adresse("987 Maple Avenue")
                        .telephone("555-7890")
                        .cin("IJ468135")
                        .cne("L975318")
                        .email("ava.davis@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(13.9)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2015")
                        .etablissementBac("Lycée")
                        .villeBac("Paris")
                        .paysBac("France")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.MST)
                        .filiereId(6L)
                        .build(),
                Inscription.builder()
                        .nom("Liam")
                        .prenom("Wilson")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1992, 9, 21).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Toronto")
                        .adresse("567 Cherry Lane")
                        .telephone("555-2345")
                        .cin("KL357246")
                        .cne("N791624")
                        .email("liam.wilson@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(18.3)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2010")
                        .etablissementBac("Secondary School")
                        .villeBac("Toronto")
                        .paysBac("Canada")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.DEUST)
                        .filiereId(7L)
                        .build()
        );
    }

    public static List<Inscription> generateInscriptionLST() {

        return List.of(
                Inscription.builder()
                .nom("Radouane")
                .prenom("Radouane")
                .genre(Gender.MALE)
                .dateNaissance(Date.from(LocalDate.of(1995, 8, 10).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                .lieuNaissance("Casablanca")
                .adresse("Casablanca")
                .telephone("0600000000")
                .cin("EE000000")
                .cne("G000000")
                .email("radouane@gmai.com")
                .filiereBac(Bac.SCIENCES_MATHS)
                .moyenneBac(15.5)
                .moyenneDiplome(16.5)
                .mentionBac(Mention.BIEN)
                .anneeBac("2013")
                .etablissementBac("Lycée")
                .villeBac("Casablanca")
                .paysBac("Maroc")
                .diplomeDeust(DiplomeDEUST.MIP)
                .mentionDiplome(Mention.BIEN)
                .anneeDiplome("2015")
                .etablissementDiplome("Faculté")
                .villeDiplome("Casablanca")
                .paysDiplome("Maroc")
                .isAccepted(false)
                .isRefused(false)
                .isCanceled(false)
                .diplomat(Diplomat.LST)
                .filiereId(1L)
                .build(),
                Inscription.builder()
                        .nom("Alice")
                        .prenom("Johnson")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1998, 5, 15).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("New York")
                        .adresse("123 Main Street")
                        .telephone("1234567890")
                        .cin("AA123456")
                        .cne("G111111")
                        .email("alice@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(14.2)
                        .moyenneDiplome(15.8)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2016")
                        .etablissementBac("High School")
                        .villeBac("New York")
                        .paysBac("USA")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2018")
                        .etablissementDiplome("University")
                        .villeDiplome("New York")
                        .paysDiplome("USA")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(1L)
                        .build(),
                Inscription.builder()
                        .nom("Robert")
                        .prenom("Smith")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1990, 12, 3).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Los Angeles")
                        .adresse("456 Elm Street")
                        .telephone("9876543210")
                        .cin("BB987654")
                        .cne("G222222")
                        .email("robert@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(17.9)
                        .moyenneDiplome(18.3)
                        .mentionBac(Mention.TRES_BIEN)
                        .anneeBac("2008")
                        .etablissementBac("High School")
                        .villeBac("Los Angeles")
                        .paysBac("USA")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2012")
                        .etablissementDiplome("University")
                        .villeDiplome("Los Angeles")
                        .paysDiplome("USA")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(2L)
                        .build(),
                Inscription.builder()
                        .nom("Sophia")
                        .prenom("Brown")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1993, 7, 20).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("London")
                        .adresse("789 Oak Avenue")
                        .telephone("5555555555")
                        .cin("CC555555")
                        .cne("G333333")
                        .email("sophia@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(16.0)
                        .moyenneDiplome(17.2)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2011")
                        .etablissementBac("High School")
                        .villeBac("London")
                        .paysBac("UK")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.TRES_BIEN)
                        .anneeDiplome("2014")
                        .etablissementDiplome("University")
                        .villeDiplome("London")
                        .paysDiplome("UK")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(3L)
                        .build(),
                Inscription.builder()
                        .nom("William")
                        .prenom("Davis")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1997, 9, 8).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Toronto")
                        .adresse("567 Pine Lane")
                        .telephone("1111111111")
                        .cin("DD111111")
                        .cne("G444444")
                        .email("william@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(15.5)
                        .moyenneDiplome(16.7)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2015")
                        .etablissementBac("High School")
                        .villeBac("Toronto")
                        .paysBac("Canada")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2017")
                        .etablissementDiplome("University")
                        .villeDiplome("Toronto")
                        .paysDiplome("Canada")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(4L)
                        .build(),
                Inscription.builder()
                        .nom("Ava")
                        .prenom("Wilson")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1994, 4, 12).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Sydney")
                        .adresse("789 Maple Street")
                        .telephone("2222222222")
                        .cin("EE222222")
                        .cne("G555555")
                        .email("ava@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(14.8)
                        .moyenneDiplome(15.9)
                        .mentionBac(Mention.ASSEZ_BIEN)
                        .anneeBac("2012")
                        .etablissementBac("High School")
                        .villeBac("Sydney")
                        .paysBac("Australia")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2014")
                        .etablissementDiplome("University")
                        .villeDiplome("Sydney")
                        .paysDiplome("Australia")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(5L)
                        .build(),
                Inscription.builder()
                        .nom("James")
                        .prenom("Anderson")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1996, 11, 25).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Berlin")
                        .adresse("456 Cedar Road")
                        .telephone("9999999999")
                        .cin("FF999999")
                        .cne("G666666")
                        .email("james@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(16.5)
                        .moyenneDiplome(17.8)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2014")
                        .etablissementBac("High School")
                        .villeBac("Berlin")
                        .paysBac("Germany")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2016")
                        .etablissementDiplome("University")
                        .villeDiplome("Berlin")
                        .paysDiplome("Germany")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(6L)
                        .build(),
                Inscription.builder()
                        .nom("Mia")
                        .prenom("Garcia")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1992, 3, 17).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Madrid")
                        .adresse("789 Willow Avenue")
                        .telephone("3333333333")
                        .cin("GG333333")
                        .cne("G777777")
                        .email("mia@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(15.0)
                        .moyenneDiplome(16.2)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2010")
                        .etablissementBac("High School")
                        .villeBac("Madrid")
                        .paysBac("Spain")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2013")
                        .etablissementDiplome("University")
                        .villeDiplome("Madrid")
                        .paysDiplome("Spain")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(7L)
                        .build(),
                Inscription.builder()
                        .nom("Ethan")
                        .prenom("Martinez")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1999, 2, 6).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Paris")
                        .adresse("567 Birch Lane")
                        .telephone("7777777777")
                        .cin("HH777777")
                        .cne("G888888")
                        .email("ethan@example.com")
                        .filiereBac(Bac.SCIENCES_EXP)
                        .moyenneBac(16.2)
                        .moyenneDiplome(17.4)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2013")
                        .etablissementBac("High School")
                        .villeBac("Paris")
                        .paysBac("France")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2015")
                        .etablissementDiplome("University")
                        .villeDiplome("Paris")
                        .paysDiplome("France")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(8L)
                        .build(),
                Inscription.builder()
                        .nom("Isabella")
                        .prenom("Lopez")
                        .genre(Gender.FEMALE)
                        .dateNaissance(Date.from(LocalDate.of(1991, 10, 4).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Rome")
                        .adresse("123 Oak Street")
                        .telephone("4444444444")
                        .cin("II444444")
                        .cne("G999999")
                        .email("isabella@example.com")
                        .filiereBac(Bac.SCIENCES_TECH)
                        .moyenneBac(15.8)
                        .moyenneDiplome(17.0)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2009")
                        .etablissementBac("High School")
                        .villeBac("Rome")
                        .paysBac("Italy")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2012")
                        .etablissementDiplome("University")
                        .villeDiplome("Rome")
                        .paysDiplome("Italy")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(9L)
                        .build(),
                Inscription.builder()
                        .nom("Noah")
                        .prenom("Gonzalez")
                        .genre(Gender.MALE)
                        .dateNaissance(Date.from(LocalDate.of(1993, 6, 9).atStartOfDay().toInstant(java.time.ZoneOffset.UTC)))
                        .lieuNaissance("Tokyo")
                        .adresse("789 Cherry Avenue")
                        .telephone("6666666666")
                        .cin("JJ666666")
                        .cne("G101010")
                        .email("noah@example.com")
                        .filiereBac(Bac.SCIENCES_MATHS)
                        .moyenneBac(16.7)
                        .moyenneDiplome(18.0)
                        .mentionBac(Mention.BIEN)
                        .anneeBac("2011")
                        .etablissementBac("High School")
                        .villeBac("Tokyo")
                        .paysBac("Japan")
                        .diplomeDeust(DiplomeDEUST.MIP)
                        .mentionDiplome(Mention.BIEN)
                        .anneeDiplome("2014")
                        .etablissementDiplome("University")
                        .villeDiplome("Tokyo")
                        .paysDiplome("Japan")
                        .isAccepted(false)
                        .isRefused(false)
                        .isCanceled(false)
                        .diplomat(Diplomat.LST)
                        .filiereId(10L)
                        .build()

        );
    }
}
